spring:
  cloud:
    consul:
      discovery:
        enabled: true
      config:
        enabled: false
  management:
    endpoints:
      web:
        exposure:
          include: health,info
  health:
    db:
      enabled: true
    ping:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
