spring:
  cloud:
    consul:
      discovery:
        enabled: true
      config:
        enabled: false
  management:
    endpoints:
      web:
        exposure:
          include: health,info
  health:
    db:
      enabled: true
    ping:
      enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
