management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true # Ensure gateway-specific actuator endpoints are enabled

spring:
  cloud:
    gateway:
      filter:
        remove-filtered-headers: false

      default-filters:
        - PreserveHostHeader



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
