spring:
  cloud:
    consul:
      discovery:
        enabled: true
      config:
        enabled: false # Désactivez cela si vous n'utilisez pas le service de configuration Consul
  management:
    endpoints:
      web:
        exposure:
          include: health,info # Assurez-vous que les endpoints de santé sont exposés

management:
  health:
    # Configurez votre check de santé ici
    db:
      enabled: true
    ping:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

